### ISSUE TITLE
Suggestion 无法通过键盘操控

### ISSUE THREAD

**Issue by flyrun9527** [wzc520pyfm/ant-design-x-vue#375]
ant design x 可以用键盘操控
https://x.ant.design/components/suggestion-cn

**Comment by flyrun9527** [comment]
底层的级联如果采用cascader 即可实现功能 https://www.antdv.com/components/cascader-cn

**Comment by yuxi-ovo** [comment]
#347

**Comment by chinfeng** [comment]
更新一下，测试是可以用键盘上下控制选项的，但是ui 的高亮状态没有更新。比方说菜单弹出后先按一下下箭头，然后回车，会发现输入更新的是第二个选项的 value。

**Comment by lilirg** [comment]
我觉得如果急着实现键盘效果的话，可以用[aria-checked="true"]先处理一下

**Comment by chinfeng** [comment]
> 我觉得如果急着实现键盘效果的话，可以用[aria-checked="true"]先处理一下

是的，目前我使用全局样式来暂时修复，但这只是临时方案。

```css
.ant-cascader-menu-item[aria-checked="true"] {
  font-weight: 600;
  background-color: #e6f4ff;
}

.ant-cascader-menu-item.ant-cascader-menu-item-active[aria-checked="false"] {
  font-weight: inherit;
  background-color: inherit;
}
```
